# Generated by Django 2.2.7 on 2020-02-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='upload_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
