# Generated by Django 2.2.7 on 2020-02-19 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import headway.models


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0002_auto_20200218_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=150, upload_to=headway.models.upload_dir_papers)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headway.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='program',
        ),
        migrations.AlterField(
            model_name='test',
            name='credit',
            field=models.IntegerField(blank=True, default=10, help_text='Credit for this Test. Enter a number from 0 to 10depending on the weight this test will contribute tothe final(Aggregated) test score for this course.', null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='upload_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Papars',
        ),
        migrations.AddField(
            model_name='testgrade',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headway.Test'),
        ),
    ]
