# Generated by Django 2.2.7 on 2020-02-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0003_auto_20200219_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploads',
            options={'verbose_name_plural': 'Uploads'},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='student',
            name='computer_num',
            field=models.CharField(blank=True, default='ST0001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='headway.Lecturer'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
