# Generated by Django 2.2.7 on 2020-02-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0004_auto_20200226_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
