# Generated by Django 2.2.7 on 2020-03-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0006_auto_20200301_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='nrc_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='nrc_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nrc_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='courseregister',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_course', to='headway.Course'),
        ),
        migrations.AlterField(
            model_name='courseregister',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register', to='headway.Student'),
        ),
    ]
