# Generated by Django 2.2.7 on 2020-03-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0007_auto_20200326_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='computer_num',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
