# Generated by Django 2.2.7 on 2020-04-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0014_auto_20200409_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='courses',
            field=models.ManyToManyField(to='headway.Course'),
        ),
    ]
