# Generated by Django 2.2.7 on 2020-04-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0015_exam_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='trail',
        ),
        migrations.AlterField(
            model_name='institution',
            name='active_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GradingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headway.Institution')),
            ],
        ),
    ]
