# Generated by Django 2.2.7 on 2020-04-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headway.Student'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
