# Generated by Django 2.2.7 on 2020-04-28 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0015_exam_courses'),
        ('administrator', '0003_invoice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='headway.Institution'),
            preserve_default=False,
        ),
    ]
